const state={words:[],list:[],card:null};const $=id=>document.getElementById(id);
async function init(){state.words=await (await fetch('vocabulary.json')).json();fill('level',unique(state.words.map(x=>x.Level)));$('level').value='A1';updateSublevels();bind();render()}
const unique=a=>[...new Set(a)];function fill(id,values){const el=$(id);el.innerHTML='';values.forEach(v=>el.add(new Option(v,v)))}
function updateSublevels(){const level=$('level').value;fill('sublevel',unique(state.words.filter(x=>x.Level===level).map(x=>x.Sublevel)));updateUnits()}
function updateUnits(){const f=state.words.filter(x=>x.Level===$('level').value&&x.Sublevel===$('sublevel').value);fill('unit',unique(f.map(x=>String(x.Unit))));render()}
function current(){return state.words.filter(x=>x.Level===$('level').value&&x.Sublevel===$('sublevel').value&&String(x.Unit)===$('unit').value)}
function image(x){return x.ImageUrl||'https://source.unsplash.com/600x400/?'+encodeURIComponent(x.Word)}
function speak(word){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(word);u.lang='en-US';u.rate=Number($('speed').value);speechSynthesis.speak(u)}
function translation(x){return x.Translation?x.Translation:'Traducción pendiente de completar en Microsoft Lists'}
function render(){const list=current();state.list=list;$('count').textContent=list.length+' palabras · '+$('sublevel').value+' · unidad '+$('unit').value;$('grid').innerHTML=list.map(x=>'<article class="card"><img loading="lazy" src="'+image(x)+'" alt="'+x.Word+'"><div class="card-body"><div class="word">'+x.Word+'</div><div class="translation '+(x.Translation?'':'pending')+'">'+translation(x)+'</div><div class="meta">'+x.Level+' · '+x.Sublevel+' · Unidad '+x.Unit+'</div><div class="card-actions"><button class="audio" data-word="'+encodeURIComponent(x.Word)+'">🔊 Escuchar</button><button class="btn-card" data-title="'+x.Title+'">🎴 Usar tarjeta</button></div></div></article>').join('');document.querySelectorAll('.audio').forEach(b=>b.onclick=()=>speak(decodeURIComponent(b.dataset.word)));document.querySelectorAll('.btn-card').forEach(b=>b.onclick=()=>showCard(state.list.find(x=>x.Title===b.dataset.title)));newCard()}
function showCard(x){if(!x)return;state.card=x;$('flashcard').className='flashcard';$('flashcard').innerHTML='<div class="flashcard-inner"><div class="flashcard-face front"><img src="'+image(x)+'" alt="'+x.Word+'"><div class="word">'+x.Word+'</div><small>Haz clic para girar</small><div class="flashcard-actions"><button class="audio-card">🔊 Escuchar</button></div></div><div class="flashcard-face back"><div class="word">'+x.Word+'</div><div class="translation">'+translation(x)+'</div><small>Haz clic para volver</small></div></div>';$('flashcard').onclick=e=>{if(!e.target.closest('button'))$('flashcard').classList.toggle('flipped')};$('flashcard').querySelector('.audio-card').onclick=e=>{e.stopPropagation();speak(x.Word)}}
function newCard(){const list=state.list;if(list.length)showCard(list[Math.floor(Math.random()*list.length)])}function bind(){$('level').onchange=()=>{updateSublevels()};$('sublevel').onchange=()=>{updateUnits()};$('unit').onchange=render;$('newCard').onclick=newCard;$('stopAudio').onclick=()=>speechSynthesis.cancel();$('flashcard').onkeydown=e=>{if(e.key==='Enter'||e.key===' ')$('flashcard').classList.toggle('flipped')}}init();