const state={words:[],list:[],card:null,selected:[]};const $=id=>document.getElementById(id);function renderSelected(){}
async function init(){state.words=await (await fetch('vocabulary.json')).json();fill('level',unique(state.words.map(x=>x.Level)));$('level').value='A1';updateSublevels();bind();render()}
const unique=a=>[...new Set(a)];function fill(id,values){const el=$(id);el.innerHTML='';values.forEach(v=>el.add(new Option(v,v)))}
function updateSublevels(){const level=$('level').value;fill('sublevel',unique(state.words.filter(x=>x.Level===level).map(x=>x.Sublevel)));updateUnits()}
function updateUnits(){const f=state.words.filter(x=>x.Level===$('level').value&&x.Sublevel===$('sublevel').value);fill('unit',unique(f.map(x=>String(x.Unit))));render()}
function current(){return state.words.filter(x=>x.Level===$('level').value&&x.Sublevel===$('sublevel').value&&String(x.Unit)===$('unit').value)}
function image(x){return x.ImageUrl||'https://source.unsplash.com/600x400/?'+encodeURIComponent(x.Word)}
function speak(word){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(word);u.lang='en-US';u.rate=Number($('speed').value);speechSynthesis.speak(u)}
function translation(x){return x.Translation?x.Translation:'Traducción pendiente de completar en Microsoft Lists'}
function render(){const list=current();state.list=list;$('count').textContent=list.length+' palabras · '+$('sublevel').value+' · unidad '+$('unit').value;$('grid').innerHTML=list.map(x=>'<article class="card"><img loading="lazy" src="'+image(x)+'" alt="'+x.Word+'"><div class="card-body"><div class="word">'+x.Word+'</div><div class="translation '+(x.Translation?'':'pending')+'">'+translation(x)+'</div><div class="meta">'+x.Level+' · '+x.Sublevel+' · Unidad '+x.Unit+'</div><div class="card-actions"><button class="audio" data-word="'+encodeURIComponent(x.Word)+'">🔊 Escuchar</button><button class="btn-card" data-title="'+x.Title+'">📌 Agregar a mi lista</button></div></div></article>').join('');document.querySelectorAll('.audio').forEach(b=>b.onclick=()=>speak(decodeURIComponent(b.dataset.word)));document.querySelectorAll('.btn-card').forEach(b=>b.onclick=()=>addSelected(state.list.find(x=>x.Title===b.dataset.title)));renderSelected();newCard()}
function showCard(x){if(!x)return;state.card=x;$('flashcard').className='flashcard';$('flashcard').innerHTML='<div class="flashcard-inner"><div class="flashcard-face front"><img src="'+image(x)+'" alt="'+x.Word+'"><div class="word">'+x.Word+'</div><small>Haz clic para girar</small><div class="flashcard-actions"><button class="audio-card">🔊 Escuchar</button></div></div><div class="flashcard-face back"><div class="word">'+x.Word+'</div><div class="translation">'+translation(x)+'</div><small>Haz clic para volver</small></div></div>';$('flashcard').onclick=e=>{if(!e.target.closest('button'))$('flashcard').classList.toggle('flipped')};$('flashcard').querySelector('.audio-card').onclick=e=>{e.stopPropagation();speak(x.Word)}}
function newCard(){const list=state.list;if(list.length)showCard(list[Math.floor(Math.random()*list.length)])}function bind(){$('level').onchange=()=>{updateSublevels()};$('sublevel').onchange=()=>{updateUnits()};$('unit').onchange=render;$('newCard').onclick=newCard;$('stopAudio').onclick=()=>speechSynthesis.cancel();$('flashcard').onkeydown=e=>{if(e.key==='Enter'||e.key===' ')$('flashcard').classList.toggle('flipped')}}init();
let game={items:[],current:null,score:0,round:0};function shuffle(a){return [...a].sort(()=>Math.random()-.5)}function startGame(selected){game.items=state.list.length?state.list:current();game.score=0;game.round=0;nextQuestion(selected)}function nextQuestion(selected){const pool=game.items.filter(x=>x.Translation);game.current=selected||pool[Math.floor(Math.random()*pool.length)];if(!game.current)return;$('gameWord').textContent='Escucha y selecciona el significado';$('gameScore').textContent='Puntos: '+game.score;$('gameProgress').textContent='Pregunta '+(game.round+1);$('gameFeedback').textContent='';$('gameFeedback').className='game-feedback';const distractors=shuffle(pool.filter(x=>x.Title!==game.current.Title)).slice(0,3);const options=shuffle([game.current,...distractors]);$('gameOptions').innerHTML=options.map(x=>'<button class="game-option" data-title="'+x.Title+'">'+x.Translation+'</button>').join('');document.querySelectorAll('.game-option').forEach(b=>b.onclick=()=>answer(b,game.current));speak(game.current.Word)}function answer(button,correct){if(document.querySelector('.game-option.correct,.game-option.incorrect'))return;const ok=button.dataset.title===correct.Title;button.classList.add(ok?'correct':'incorrect');if(ok){game.score++;$('gameFeedback').textContent='✅ Correcto: '+correct.Word;$('gameFeedback').className='game-feedback success'}else{$('gameFeedback').textContent='❌ La respuesta correcta es: '+correct.Translation;$('gameFeedback').className='game-feedback error';document.querySelector('[data-title="'+correct.Title+'"]').classList.add('correct')}game.round++;setTimeout(()=>nextQuestion(),1100)}$('newGame').onclick=()=>startGame();$('gameListen').onclick=()=>game.current&&speak(game.current.Word);$('gameSlow').onclick=()=>{if(!game.current)return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(game.current.Word);u.lang='en-US';u.rate=.85;speechSynthesis.speak(u)};
